### ISSUE TITLE
Issues with ed

### ISSUE THREAD

**Issue by svhum** [SamCoVT/TaliForth2#6]
I've noticed some strange behaviour with ed. First, it seems ed does not work well if Tali is in hex mode when ed is started (I only discovered this because I was already in hex mode incidentally). For example, 
```
hex  ok                                                      
ed                                                           
a                                                            
?                                                            
Q  ok
```
However, even in decimal mode, I am not able to get expected behaviour. For example,
```
decimal  ok
ed 
a 
One 
Two 
. 
,p 
One
Two
n 
0 A�$��}rA����
```
which shows the current line does not seem to be updating properly. 

I tried running the ed.fs test script (when in decimal mode) and it produced the output attached showing a number of failed tests. Any help would be appreciated! I am using the `master-ophis` branch.
[ed.txt](https://github.com/SamCoVT/TaliForth2/files/10109739/ed.txt)

**Comment by SamCoVT** [comment]
Hi @svhum,
ed uses Tali's number handling - because of that "a" is a number when in hex.  A proposed solution for that might be to save the current base, switch to decimal while using ed, and then put the base back when done.

I've verified that there does appear to be a bug with n.  In particular, having no argument to n should print all of the lines (I think - I'll have to go back and read ed's man page again).  It looks like the code is trying/supposed to recognize that situation and failing and is thus printing line 0 (except there isn't a line 0, which is why you get gobbledy-goo after the 0).  I don't see "n" tested without any line parameters in front of it, so it looks like an untested case.  I do see tests for n with 1 or two line numbers in front and I believe those pass.

In terms of the tests failing in your sample results, it looks like there are extra lines in the tests (which increases the number of characters written when saved to RAM) and that's why the test fails.  Here's a snippet from my running of the ed tests (which all pass) to show the difference (note how many "ok"s there are).  I'm going to guess you are working on Windows and your terminal software is sending both CR and LF characters at the end of each line?  Ideally, you'll want to set your terminal to just send LF for line endings.
```
testing editor words: ed  ok
  ok
decimal  ok
marker ed-tests   ok
  ok
\ Use 10000 (decimal) as write area. This may have to be changed if tests crash  ok
\ to a higher value. Currently, we are already using 7000 (check with HERE).  ok
\ Note ed tests will usually return with ( 0 0 ) on the stack because of the   ok
\ target address  ok
  ok
\ === SIMPLE TESTS ===  ok
  ok
\ --- a command ---  ok
  ok
\ Simple adding of text; want aaaa bbbb  ok
ed 
a 
aaaa 
bbbb 
. 
10000w 
10 
q  ok
  ok
T{ 10000 10  s\" aaaa\nbbbb\n" compare -> 10000 10 0 }T  ok
```

**Comment by svhum** [comment]
Hi @SamCoVT,

Thanks for having a look. I had the impression from the Tali documentation using n with no argument would have it act on the current line. In any case, if supplied with arguments, it seems to work fine.

You're right about the extra CRs - good catch. I am using ascii-xfr to send .fs files, and I forgot the default behaviour is to terminate lines with CRLF. By adding the -n flag, it will only send LFs, and then the ed.fs tests all pass.

**Comment by SamCoVT** [comment]
I haven't touched the hex/decimal issue, but I believe I've fixed the n and p with no line numbers issue.  I also made them set the current line to the last one printed, as that is what GNU ed does.  Can you check out branch bugfix/ed_svhum-ophis (or just grab ed.asm from https://github.com/SamCoVT/TaliForth2/tree/bugfix/ed_svhum-ophis) and give it a try?

Also, what do you think should be done about the hex issue.  Reasonable solutions might include:
A) Put in the documentation to use decimal.
B) Switch to decimal when starting ed and put it back when quitting ed.

**Comment by svhum** [comment]
I tried it and it works, thanks!

For the hex issue, B) seems the most resilient way to solve the problem in case other less experienced users like me accidentally run ed in hex mode! Unless there is some good reason to ed running in hex mode.

**Comment by svhum** [comment]
Also, I noticed the docs do warn that "ed currently only works with decimal numbers. When in doubt, use decimal to make sure you’re using base ten," though it's unclear that ed's commands (vs. line numbers) will also not work  if ed is started in hex mode.

**Comment by SamCoVT** [comment]
The master-64tass and master-ophis branches should now have this fixed.  There was one unused byte left in the editor variables, so I used it to save/restore the BASE.  All numbers in ed will be in decimal (including the address used with W, and I updated the docs to mention that).
